# Generated by Django 3.0.7 on 2020-06-28 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='works',
            name='image',
            field=models.ImageField(default=None, max_length='50', upload_to='pics'),
            preserve_default=False,
        ),
    ]
