# Generated by Django 3.0.7 on 2020-06-28 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0002_works_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='works',
            old_name='image',
            new_name='images',
        ),
    ]
