# Generated by Django 3.0.7 on 2020-06-28 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0003_auto_20200628_0728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='works',
            name='images',
        ),
    ]
