# Generated by Django 3.0.7 on 2020-06-28 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0008_works_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works',
            name='discrib',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='works',
            name='image',
            field=models.ImageField(default='asd', max_length=50, upload_to='pics'),
        ),
    ]
