# Generated by Django 3.0.7 on 2020-06-28 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0009_auto_20200628_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='works',
            name='links',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
    ]
