# Generated by Django 3.0.7 on 2020-06-29 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0010_works_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('tech', models.CharField(max_length=15)),
                ('describ', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
