# Generated by Django 3.0.7 on 2020-06-29 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0011_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='link',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
