# Generated by Django 3.0.7 on 2020-06-29 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0012_auto_20200629_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='link',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
